### ISSUE TITLE
Execution Instances Management

### ISSUE THREAD

**Issue by Thilakraj1998** [blobcity/autoai#10]
file to refer: 
   
    https://github.com/blobcity/autoai/blob/main/blobcity/store/DictClass.py

            YAML=dict()
            ObjectExist= False
            ObjectList=None
            def __int__(self):
                self.ObjectExist=False
                self.ObjectList=None

    https://github.com/blobcity/autoai/blob/main/blobcity/blobcity.py

Reset following Class data in the `DictClass.py` file for each call of the `train` in `blobcity.py` function to avoid execution failure due to data transfer between function calls.

**Comment by aadityasinha-dotcom** [comment]
I think this issue has been resolved?

**Comment by Thilakraj1998** [comment]
Yes
