### ISSUE TITLE
Confusion Matrix

### ISSUE THREAD

**Issue by sanketsarang** [blobcity/autoai#108]
Add support to print a Confusion Matrix for Classification type of problems.

## Example Use
```Python
model = bc.train("classification_data.csv", "target_column")
model.confusionMatrix()
```

The matrix should be displayed as a matplotlib chart.

## Error Conditions
Calling the `confusionMatrix()` function for a Regression problem must throw an error stating `Confusion matrix is available only for Classification problems`

files to refer:

* https://github.com/blobcity/autoai/blob/main/blobcity/store/Model.py
* https://github.com/blobcity/autoai/blob/main/blobcity/config/tuner.py

**Comment by naresh1205** [comment]
Hey, I am new to open source and would like to contribute to your project.

In the sample_use.py code does the bc.train(...) method return a modelClass?

Also, do you need the code for the confusion matrix as well? If yes, then the code has to be written in Model.py (model class) right?

**Comment by Thilakraj1998** [comment]
> Hey, I am new to open source and would like to contribute to your project.
> 
> In the sample_use.py code does the bc.train(...) method return a modelClass?
> 
> Also, do you need the code for the confusion matrix as well? If yes, then the code has to be written in Model.py (model class) right?

Yes bc.train() returns modelClass, and Model.py should have the function for confusion matrix

**Comment by sanketsarang** [comment]
@naresh1205 you want to take up this task? We can assign it to you, and help you along the way to make a contribution.

**Comment by aadityasinha-dotcom** [comment]
> > Is this issue open? @sanketsarang
> 
> Yes
> 

Can I work on this issue?
