### ISSUE TITLE
Fix Import Statement

### ISSUE THREAD

**Issue by Thilakraj1998** [blobcity/autoai#12]
Currently import statement to import the library is:

    import blobcity.blobcity as bc

Change this statement to :

    import blobcity as bc

And fix the driver module `driver.py` files path associate to import fix.

**Comment by sanketsarang** [comment]
@sreyan-ghosh the task is yours!

**Comment by Thilakraj1998** [comment]
@sreyan-ghosh Sorry to inform you a bit late the issue has been resolved for the initial release of the library on PyPi
