### ISSUE TITLE
Fix YAML file storage path

### ISSUE THREAD

**Issue by Thilakraj1998** [blobcity/autoai#13]
file to refer : https://github.com/blobcity/autoai/blob/main/blobcity/utils/YamlGenerator.py
Currently after the module executes the generate `YAMl file` gets stored in API directory

           def writeYml(val):
                with open(r'./yml/Process.yaml', 'w') as file:
                    yaml.dump(val, file,sort_keys=False)

Change the path of storage to working directory

**Comment by DireWolf707** [comment]
Hye, I am new to open-source and want to contribute to this issue for hacktoberfest.
Can you assign it to me?

**Comment by sanketsarang** [comment]
@DireWolf707 absolutely! Have assigned the task to you.

**Comment by Thilakraj1998** [comment]
@DireWolf707  Sorry to inform you a bit late the issue has been resolved for the initial release of the library on PyPi
