### ISSUE TITLE
Reset DictClass.py Class Variable 

### ISSUE THREAD

**Issue by Thilakraj1998** [blobcity/autoai#14]
file to refer:  https://github.com/blobcity/autoai/blob/main/blobcity/store/DictClass.py
Reset or Clear data initialized/allotted to Class variables in `DictClass.py` on each call to `driver` function `train`

**Comment by aadityasinha-dotcom** [comment]
Can I work on this issue?

**Comment by sanketsarang** [comment]
@aadityasinha-dotcom there you go. Issue is assigned to you.

**Comment by Thilakraj1998** [comment]
@aadityasinha-dotcom  Sorry to inform you a bit late the issue has been resolved for the initial release of the library on PyPi

**Comment by aadityasinha-dotcom** [comment]
Oh. It's okay.
