### ISSUE TITLE
predict() got an unexpected keyword argument 'file'

### ISSUE THREAD

**Issue by Monishkumarvr** [blobcity/autoai#197]
I am getting this error, what am I doing wrong?

**Comment by Thilakraj1998** [comment]
@Monishkumarvr 

The predict function take following arguments 

* test = "path to your test dataset"
* return_type="list or df"
* path="output file path with extension csv,xlsx or json"

for example
```
model.predict(test="./data.csv",return_type='df'.path="./output.csv")
```

**Comment by Monishkumarvr** [comment]
Thanks! Now it's working.
