### ISSUE TITLE
Save and Load a Trained Model

### ISSUE THREAD

**Issue by Thilakraj1998** [blobcity/autoai#20]
Add functionality to save and load a trained model by using pickle or Keras function for appropriate model type, i.e. either Sci-kit learn model or Tensorflow model .

file to refer : https://github.com/blobcity/autoai/blob/main/blobcity/store/Model.py

Add function `save` and `load` in the `Model.py` file
Required functionality for `save` function:

1. takes single string  argument, which is path to save model, along with filename for example:
   
            save("path/filename")   
2. If path not specified in argument, utilize default path and default name to save in working directory. And print/log of absolute path for the file.
3. identify type of model saving strategy to use, i.e. whether use `pickle or Keras` to save model.
 
Required functionality for `load` function:

1. takes single string  argument, which is path of saved model file:

             load("path/filename.pkl")   or  load("path/filename.h5") 
2. on the basis of file extension use appropriate loading strategy either `pickle or Keras` load functions 
3. return the `model`.

**Comment by sreyan-ghosh** [comment]
Hi, can you assign this to me, please?

I'm hoping a simple `pickle.dumps('my_model.pkl')` does the job. The final addition would look something like this:

```py
def save(self, path_pref='./'):
  final_path = os.path.join(path_pref, 'my_model.pkl')
  pickle.dumps(final_path)
  # print(final_path)
  return final_path
```

Is this fine?

**Comment by aadityasinha-dotcom** [comment]
Can I work on this issue?

**Comment by sreyan-ghosh** [comment]
Hi, I have updated my fork of this repo as per the changes made to the issue. I have done it using pickle and h5 files and also included type checking for Keras models in the case of .h5 files.
