### ISSUE TITLE
Additional requirements needed for running the tests

### ISSUE THREAD

**Issue by SkBlaz** [blobcity/autoai#208]
Hello `autoai` team! Great work. Whilst running the tests, I'm noting that requirements do not really cover everything needed.
Examples include:

1. autokeras (`>=1.0.16.post1`) -> this is quite a substantial one, possibly dependent on the present hardware (works on CPUs for me out of the box)
2. nbformat (`>=5.1.3`)
3. requests (this is not native to e.g., a generic conda env) (`>=2.26.0`)

Hope this helps

**Comment by Thilakraj1998** [comment]
> 

keeping autokeras or tensorflow installation in the setup.config causing cyclic installation, which substantial increases the installation time of the library. Thats why it is not included in the setup file currently.

**Comment by Thilakraj1998** [comment]
@SkBlaz  Added nbformat and requests has suggested
