### ISSUE TITLE
Add Perceptron Classifier

### ISSUE THREAD

**Issue by sanketsarang** [blobcity/autoai#37]
Add Simple Perceptron Classifier model into the library. 

Primary File to Change: https://github.com/blobcity/autoai/blob/main/blobcity/config/classifier_config.py 

Reference Perceptron Implementation:
https://github.com/blobcity/ai-seed/blob/main/Classification/Linear%20Models/Perceptron.ipynb

Dependencies if any, must be appropriately added. Test run of the `train` function on a classification problem must pass, and the function must attempt to train a perceptron as a potential best fit model.

**Comment by SaharshLaud** [comment]
Can you assign this to me @sanketsarang sir?
I will work on the issue and provide the required code for fixing it.
