### ISSUE TITLE
Add SGDClassifier

### ISSUE THREAD

**Issue by sanketsarang** [blobcity/autoai#38]
Add SGDClassifier model into the library.

Primary File to Change: https://github.com/blobcity/autoai/blob/main/blobcity/config/classifier_config.py

Reference SGDClassifier Implementation:
https://github.com/blobcity/ai-seed/blob/main/Classification/Linear%20Models/SGDClassifier.ipynb

Dependencies if any, must be appropriately added. Test run of the train function on a classification problem must pass, and the function must attempt to train an SGDClassifier as a potential best fit model.

**Comment by Devolta05** [comment]
Hello, Could I contribute to this issue? if possible could it be assigned to me :thinking:

**Comment by sanketsarang** [comment]
Done. Assigned to you @Devolta05
