### ISSUE TITLE
Add AdaBoostClassifier

### ISSUE THREAD

**Issue by sanketsarang** [blobcity/autoai#39]
Add AdaBoostClassifier model into the library.

Primary File to Change: https://github.com/blobcity/autoai/blob/main/blobcity/config/classifier_config.py

Reference AdaBoostClassifier Implementation:
https://github.com/blobcity/ai-seed/blob/main/Classification/Adaptive%20Boosting/AdaBoostClassifier.ipynb

Dependencies if any, must be appropriately added. Test run of the train function on a classification problem must pass, and the function must attempt to train an AdaBoostClassifier as a potential best fit model.

**Comment by melan96** [comment]
@sanketsarang, can you assign me this issue?  so i can implement the solution for it

**Comment by melan96** [comment]
@sanketsarang fixes PR was added to codebase. #77
