### ISSUE TITLE
Add CatBoostClassifier

### ISSUE THREAD

**Issue by sanketsarang** [blobcity/autoai#40]
Add CatBoostClassifier model into the library.

Primary File to Change: https://github.com/blobcity/autoai/blob/main/blobcity/config/classifier_config.py

Reference CatBoostClassifier Implementation:
https://github.com/blobcity/ai-seed/blob/main/Classification/CatBoost/CatBoostClassifier.ipynb

Dependencies if any, must be appropriately added. Test run of the train function on a classification problem must pass, and the function must attempt to train a CatBoostClassifier as a potential best fit model.

**Comment by balamurugan1603** [comment]
Assign me. I will do this.
