### ISSUE TITLE
Add HistGradientBoostingClassifier

### ISSUE THREAD

**Issue by sanketsarang** [blobcity/autoai#41]
Add HistGradientBoostingClassifier model into the library.

Primary File to Change: https://github.com/blobcity/autoai/blob/main/blobcity/config/classifier_config.py

Reference HistGradientBoostingClassifier Implementation:
https://github.com/blobcity/ai-seed/blob/main/Classification/Histogram-Based%20Gradient%20Boosting%20Trees/HistGradientBoostingClassifier.ipynb

Dependencies if any, must be appropriately added. Test run of the train function on a classification problem must pass, and the function must attempt to train an HistGradientBoostingClassifier as a potential best fit model.

**Comment by Devolta05** [comment]
Hello, I would like to work on this issue. Could this be assigned to me? 
I have a few question in regards to the project. I am not able to find any documentation for the same (README works but I would like to understand how it is able to find the correct model to fit for the data?). Do I need to have any prior information about the model implementation or the python notebook shared would suffice?

**Comment by sanketsarang** [comment]
@Devolta05 issue is now allotted to you. 

The project is new and we are still in the process of adding Wikis on the internal working. You can look at the `modelSearch` function inside this file for a better understanding of how the training actually happens: https://github.com/blobcity/autoai/blob/main/blobcity/main/modelSelection.py 

For this task, you are not expected to change the `modelSearch` or the driver functionality. Just adding the extra configuration in the dictionary, along with adding any required dependencies should suffice.

**Comment by Devolta05** [comment]
#85 Has been merged with the functionality of this Issue. This can be closed in my opinion :thinking:
