### ISSUE TITLE
Add LightGBMClassifier

### ISSUE THREAD

**Issue by sanketsarang** [blobcity/autoai#42]
Add LightGBMClassifier model into the library.

Primary File to Change: https://github.com/blobcity/autoai/blob/main/blobcity/config/classifier_config.py

Reference LightGBMClassifier Implementation:
https://github.com/blobcity/ai-seed/blob/main/Classification/LightGBM/LGBMClassifier.ipynb

Dependencies if any, must be appropriately added. Test run of the train function on a classification problem must pass, and the function must attempt to train a LightGBMClassifier as a potential best fit model.

**Comment by balamurugan1603** [comment]
Assign me. I will do this.
