### ISSUE TITLE
Add BernoulliNB Classifier

### ISSUE THREAD

**Issue by sanketsarang** [blobcity/autoai#43]
Add BernoulliNB Classifier model into the library.

Primary File to Change: https://github.com/blobcity/autoai/blob/main/blobcity/config/classifier_config.py

Reference BernoulliNB Classifier Implementation:
https://github.com/blobcity/ai-seed/blob/main/Classification/Naive%20Bayes/BernoulliNB.ipynb

Dependencies if any, must be appropriately added. Test run of the train function on a classification problem must pass, and the function must attempt to train a BernoulliNB Classifier as a potential best fit model.

**Comment by melan96** [comment]
@sanketsarang, I go through the codebase and the issue page. I can work on this issue. Could you please assign me for this task?

**Comment by sanketsarang** [comment]
@melan96 done. Assigned to you.

**Comment by melan96** [comment]
@sanketsarang this issue already merged on main source by #55

**Comment by melan96** [comment]
@Thilakraj1998 This issue already solved and merged on main source by #55.
