### ISSUE TITLE
Add GaussianNB Classifier

### ISSUE THREAD

**Issue by sanketsarang** [blobcity/autoai#45]
Add GaussianNB Classifier model into the library.

Primary File to Change: https://github.com/blobcity/autoai/blob/main/blobcity/config/classifier_config.py

Reference GaussianNB Classifier Implementation:
https://github.com/blobcity/ai-seed/blob/main/Classification/Naive%20Bayes/GaussianNB.ipynb

Dependencies if any, must be appropriately added. Test run of the train function on a classification problem must pass, and the function must attempt to train a GaussianNB Classifier as a potential best fit model.

**Comment by palankit** [comment]
Please assign this to me
