### ISSUE TITLE
Add NearestCentroid Classifier

### ISSUE THREAD

**Issue by sanketsarang** [blobcity/autoai#47]
Add NearestCentroid Classifier model into the library.

Primary File to Change: https://github.com/blobcity/autoai/blob/main/blobcity/config/classifier_config.py

Reference NearestCentroid Classifier Implementation:
https://github.com/blobcity/ai-seed/blob/main/Classification/Nearest%20Centroid/NearestCentroidClassifier.ipynb

Dependencies if any, must be appropriately added. Test run of the train function on a classification problem must pass, and the function must attempt to train a NearestCentroid Classifier as a potential best fit model.

**Comment by Tanuj2552** [comment]
Please assign me this issue, I will do the best possible. 
Btw, can I test the model on any publicly accessible data set right?

**Comment by sanketsarang** [comment]
Done, assigned to you @Tanuj2552. Yes, try on any public classification dataset. We are also setting up some test scripts. If those get done before, you can use them.

**Comment by Tanuj2552** [comment]
Commit with PR #78 added to solve this

**Comment by Tanuj2552** [comment]
New commit with PR #88 added to solve this issue after a discussion on PR #78
