### ISSUE TITLE
Parallel Processing/Execution

### ISSUE THREAD

**Issue by Thilakraj1998** [blobcity/autoai#8]
File to refer: https://github.com/blobcity/autoai/blob/main/blobcity/modelSelection.py

          modelScore={m:cvScore(models[m][0](),X,Y,k) for m in best }

The following line of code sequentially trains different machine learning models from the dictionary object (variable: best ). Instead of this sequential execution of for loop, execute the above step in `parallel` considering all the CPU cores in the system.

**Comment by aadityasinha-dotcom** [comment]
Can I work on this issue?
